const mongoose = require('mongoose');

/**
 * CitizenRequest Model
 * Stores citizen-submitted development requests with AI-generated
 * categorization, severity scoring, and summary.
 * 
 * Gemini AI performs the heavy lifting here: when a citizen submits
 * raw text, Gemini analyzes it and returns structured data that
 * populates aiCategory, aiSeverity, and aiSummary fields.
 */
const citizenRequestSchema = new mongoose.Schema({
  originalText: {
    type: String,
    required: [true, 'Request text is required'],
    trim: true,
    maxlength: 2000
  },
  language: {
    type: String,
    default: 'en',
    enum: ['en', 'hi', 'ta', 'te', 'bn', 'mr', 'gu', 'kn', 'ml', 'pa', 'or', 'as']
  },
  location: {
    lat: { type: Number, required: true },
    lng: { type: Number, required: true },
    district: { type: String, required: true },
    state: { type: String, required: true }
  },
  // AI-populated fields — Gemini categorizes the raw citizen text
  aiCategory: {
    type: String,
    enum: ['Roads', 'Water', 'Healthcare', 'Electricity', 'Sanitation'],
    required: true
  },
  aiSeverity: {
    type: Number,
    min: 1,
    max: 5,
    required: true,
    comment: '1=low, 5=critical — assigned by Gemini AI'
  },
  aiSummary: {
    type: String,
    required: true,
    comment: 'Concise ~10-word English summary generated by Gemini'
  },
  timestamp: {
    type: Date,
    default: Date.now
  }
});

// Index for fast geo-queries and dashboard filtering
citizenRequestSchema.index({ 'location.district': 1, timestamp: -1 });
citizenRequestSchema.index({ aiCategory: 1 });

module.exports = mongoose.model('CitizenRequest', citizenRequestSchema);
